export enum TransactionMutation {
  SET_TRANSACTION = 'SET_TRANSACTION',
  REMOVE_ENTITIES = 'REMOVE_ENTITIES',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  SET_ACCOUNT_ENTITIES = 'SET_ACCOUNT_ENTITIES',
  SET_PENDING_TRANSACTION = 'SET_PENDING_TRANSACTION',
  UPDATE_PENDING_TRANSACTION = 'UPDATE_PENDING_TRANSACTION',
}
