export enum WalletMutation {
  SET_ENS_NAME = 'SET_ENS_NAME',
  SET_PROVIDER = 'SET_PROVIDER',
  CLEAR_PROVIDER = 'CLEAR_PROVIDER',
  SET_WALLET_ADDRESS = 'SET_ACCOUNT',
  MISMATCH_NETWORK = 'MISMATCH_NETWORK',
  SET_WALLET_BALANCE = 'SET_WALLET_BALANCE',
  SET_PROVIDER_CONNECTION = 'SET_PROVIDER_CONNECTION',
}
