export enum ApplicationMutation {
  CLEAR_PROCESSING = 'CLEAR_PROCESSING',
  SET_PROCESSING_MODAL = 'SET_PROCESSING_MODAL',
  SET_PROCESSING_INFO = 'SET_PROCESSING_INFO',
  SET_PROCESSING_STATUS = 'SET_PROCESSING_STATUS',
  SET_CONTRACT_CONSTANTS = 'SET_CONTRACT_CONSTANTS',
}
