export enum RelayerMutation {
  SET_ETH_RATE = 'SET_ETH_RATE',
  SET_RELAYERS = 'SET_RELAYERS',
  FINISH_ACTIVE_JOB = 'FINISH_ACTIVE_JOB',
  UPDATE_ACTIVE_JOB = 'UPDATE_ACTIVE_JOB',
  SET_ACTIVE_RELAYER = 'SET_ACTIVE_RELAYER',
  EDIT_RELAYERS_LIST = 'EDIT_RELAYERS_LIST',
  SET_RELAYERS_FETCHING = 'SET_RELAYERS_FETCHING',
}
